import 'package:password_manager/utils/icons.dart';
import 'package:password_manager/utils/images.dart';

enum CurrentUser {
  email,
  name,
  uid,
  masterPass,
  userProfile,
}

enum VaultMode {
  create,
  view,
  edit,
}

enum Category {
  passwords,
  banks,
  cards,
  notes,
  all,
  other,
}

Map categoryMap = {
  Category.passwords : {
    "icon" : icoPasswords,
    "value" : "Password",
  },
  Category.banks : {
    "icon" : icoBanks,
    "value" : "Bank Account",
  },
  Category.cards : {
    "icon" : icoATMCards,
    "value" : "ATM Card",
  },
  Category.notes : {
    "icon" : icoNotes,
    "value" : "Notes",
  },
  Category.all : {
    "icon" : icoAllItems,
    "value" : "All",
  },
};

Map thumbnailMap = {
  "adobe": adobeThumbnail,
  "amazon": amazonThumbnail,
  "canva": canvaThumbnail,
  "chatgpt": chatgptThumbnail,
  "chat gpt": chatgptThumbnail,
  "facebook": facebookThumbnail,
  "figma": figmaThumbnail,
  "flipkart": flipkartThumbnail,
  "github": githubThumbnail,
  "google": googleThumbnail,
  "instagram": instagramThumbnail,
  "linkedin": linkedinThumbnail,
  "mega": megaThumbnail,
  "microsoft": microsoftThumbnail,
  "notion": notionThumbnail,
  "ola": olaThumbnail,
  "oracle": oracleThumbnail,
  "snapchat": snapchatThumbnail,
  "telegram": telegramThumbnail,
  "twitter": twitterThumbnail,
  "uber": uberThumbnail,
  "udemy": udemyThumbnail,
  "zomato": zomatoThumbnail,
};

List<String> avatarList = [
  avatar01,
  avatar02,
  avatar03,
  avatar04,
  avatar05,
  avatar06,
  avatar07,
  avatar08,
  avatar09,
  avatar10,
  avatar11,
  avatar12,
  avatar13,
  avatar14,
  avatar15,
  avatar16,
  avatar17,
  avatar18,
  avatar19,
  avatar20,
  avatar21,
  avatar22,
  avatar23,
  avatar24,
  avatar25,
  avatar26,
  avatar27,
  avatar28,
  avatar29,
  avatar30,
  avatar31,
  avatar32,
  avatar33,
  avatar34,
  avatar35,
  avatar36,
  avatar37,
  avatar38,
  avatar39,
  avatar40,
  avatar41,
  avatar42,
  avatar43,
  avatar44,
  avatar45,
  avatar46,
  avatar47,
  avatar48,
  avatar49,
  avatar50,
  avatar51,
  avatar52,
  avatar53,
  avatar54,
  avatar55,
  avatar56,
  avatar57,
  avatar58,
  avatar59,
  avatar60,
];